language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - cp example.config.js config.js
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run test
