name: CI
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run build
        run: |
          echo "Starting build..."
          npm run build
          echo "Build completed. Checking contents of build directory..."
          ls -la ./build || echo "Build directory does not exist."

      - name: Show directory structure
        run: |
          echo "Showing directory structure..."
          ls -R

      - name: Verify build output
        run: |
          if [ -d "./build" ]; then
            echo "Build directory exists. Contents:"
            ls -la ./build
          else
            echo "Build directory is missing."
          fi

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Lint code
        run: npm run lint
