name: CI
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm install --legacy-peer-deps
      - run: cp example.config.js config.js
      - run: CI=false npm run build  # Set CI to false to ignore warnings

      # Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Deploy to Netlify
      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=./build --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
