name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # Set up Node.js environment
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      # Install dependencies
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # Copy configuration file
      - name: Copy Configuration File
        run: cp example.config.js config.js

      # Run tests
      - name: Run Tests
        run: npm test
        env:
          CI: true

      # List files before the build step
      - name: List Files Before Build
        run: ls -al

      # Run the build
      - name: Run Build
        run: npm run build
        env:
          CI: true

      # List files after the build step
      - name: List Files After Build
        run: ls -al

      # Check if the 'build' directory exists
      - name: Verify Build Directory
        if: ${{ success() }}
        run: |
          if [ -d "./build" ]; then
            echo "Build directory exists."
            ls -al ./build
          else
            echo "Build directory does not exist. Something went wrong."
            exit 1
          fi
