name: CI
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install --legacy-peer-deps
      - run: cp example.config.js config.js
      - run: CI=false npm run build  # Set CI to false to ignore warnings
      
      # Optionally, you can run tests here if needed
      - run: npm test
        env:
          CI: true
